# Generated by Django 4.2.16 on 2024-09-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_imagetitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="backgrounds/")),
            ],
        ),
    ]
